baseurl: "/"
languageCode: "en-us"
title: "Hypermediocrity"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: home
      url: ""
      weight: 1
    - name: about
      url: "about/"
      weight: 2
    - name: blog
      url: "posts/"
      weight: 3
    - name: publications
      url: "publications/"
      weight: 4
    - name: portfolio
      url: "portfolio/"
      weight: 5
    - name: projects
      url: "projects/"
      weight: 6
    - name: kits
      url: "kits/"
      weight: 7

params:
  description: "Nothing special, just some of my stuff"
  footer: "&copy; [Paolo Marcucci](mailto:paolo@paolomarcucci.com) 2002 -- {Year} | [Github](https://github.com/paolom) | [Twitter](https://twitter.com/paolom) | [Mastodon](https://mastodon.social/@paolom) | [RSS](/index.xml)"

markup:
  highlight:
    codeFences: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: true      